"""Static nearest-neighbor roster (generated by scripts/build_neighbors.py).

For each roster station: the 5 closest OTHER METAR airfields within 150 km, from
AWC's stationinfo catalog. Pure geography (icao, dist_km, 16-pt bearing FROM the home
station, elev_delta_m = neighbor minus home). get_nearby_obs uses this to pick which
stations to read; the OBS themselves come only from the leakage-safe DB seam, never
a live fetch. Regenerate/verify with build_neighbors.py [--check].
"""

# home_icao -> [(neighbor_icao, dist_km, bearing, elev_delta_m), ...] nearest first
NEIGHBORS: dict[str, list[tuple[str, float, str, int]]] = {
    'KWRI': [
        ('KNEL', 22.7, 'E', -9),
        ('KVAY', 22.9, 'WSW', -20),
        ('KMJX', 27.1, 'ESE', -13),
        ('KTTN', 34.7, 'NNW', 23),
        ('KPNE', 36.6, 'W', -3),
    ],
    'KMIB': [
        ('KMOT', 18.0, 'SSE', 2),
        ('K1JN', 40.5, 'W', 165),
        ('K1NN', 43.4, 'NNW', 11),
        ('K1ON', 46.2, 'N', -39),
        ('K1MN', 49.3, 'NW', 64),
    ],
    'KRCA': [
        ('KUNR', 11.7, 'SW', 35),
        ('KRAP', 13.2, 'SSE', -28),
        ('K49B', 36.9, 'NW', -7),
        ('KCUT', 61.5, 'SW', 707),
        ('KSPF', 64.5, 'NW', 198),
    ],
    'KSSC': [
        ('KSMS', 10.2, 'ENE', -18),
        ('KMMT', 31.6, 'WSW', 5),
        ('KCDN', 34.9, 'NNW', 19),
        ('KCUB', 48.7, 'W', -16),
        ('KMNI', 49.6, 'SSE', -42),
    ],
    'KDMA': [
        ('KTUS', 7.5, 'WSW', -28),
        ('KRYN', 27.4, 'W', -73),
        ('KAVQ', 41.3, 'NW', -186),
        ('KE77', 56.8, 'NNE', 185),
        ('KMZJ', 57.3, 'NW', -230),
    ],
    'KVBG': [
        ('KXVW', 1.9, 'SE', 4),
        ('KTQS', 11.6, 'SSW', -62),
        ('KVGN', 13.0, 'N', -3),
        ('KLPC', 13.3, 'SE', -70),
        ('KSMX', 21.5, 'NNE', -23),
    ],
    'KFTK': [
        ('KEKX', 24.3, 'S', 9),
        ('KSDF', 36.8, 'NE', -79),
        ('KBRY', 42.9, 'ESE', -33),
        ('KI93', 43.5, 'WSW', 510),
        ('KLOU', 45.0, 'NE', -60),
    ],
    'PAED': [
        ('PAMR', 4.0, 'S', -11),
        ('PAFR', 9.6, 'E', 52),
        ('PALH', 10.4, 'SW', -28),
        ('PANC', 13.6, 'SW', -15),
        ('PABV', 25.4, 'NE', -33),
    ],
    'PABI': [
        ('PAEI', 98.9, 'NW', -222),
        ('PAXK', 108.1, 'S', 417),
        ('PAFB', 130.5, 'NW', -251),
        ('PAFA', 137.2, 'NW', -258),
    ],
    'RJTY': [
        ('RJTC', 6.5, 'SE', -50),
        ('RJTJ', 11.8, 'NNE', -48),
        ('RJTF', 18.3, 'ESE', -99),
        ('RJTR', 26.5, 'S', -30),
        ('RJTA', 33.9, 'SSE', -70),
    ],
}


def neighbors_of(icao: str) -> list[tuple[str, float, str, int]]:
    """Nearest-neighbor rows for a station (empty list if none/off-roster)."""
    return NEIGHBORS.get(icao.upper(), [])
