"""Static nearest-radiosonde roster (generated by scripts/build_upper_air_sites.py).

For every archived station, the closest upper-air sites by great-circle distance:
  (wmo, name, dist_km, 16-pt bearing FROM the station, lat, lon), nearest first.

`wmo` is the id the `bufr` and `wyoming` get_sounding sources take. SPC's 3-letter
site ids are a DIFFERENT namespace and are NOT derivable from this table.
Distance is reported, not filtered: soundings are sparse outside CONUS and a distant
ascent is still information -- the model weighs it. Pure geography.
Regenerate/verify with build_upper_air_sites.py [--check].
"""

# station -> [(wmo, name, dist_km, bearing, lat, lon), ...] nearest first
UPPER_AIR: dict[str, list[tuple[str, str, float, str, float, float]]] = {
    'KWRI': [
        ('72501', 'UPTON; NY.', 174.1, 'ENE', 40.865, -72.8628),
        ('72402', 'WALLOPS ISLAND; VA.', 244.1, 'SSW', 37.9333, -75.4833),
        ('72403', 'WASHINGTON/DULLES INT.; VA.', 272.5, 'WSW', 38.95, -77.45),
    ],
    'KMIB': [
        ('72764', 'BISMARCK/MUN.; ND.', 186.9, 'SSE', 46.7717, -100.7594),
        ('71843', 'WINNIPEG UA; MAN', 343.2, 'ENE', 49.8, -97.1333),
        ('72768', 'GLASGOW/INT.; MT.', 391.4, 'W', 48.2067, -106.6255),
    ],
    'KRCA': [
        ('72662', 'RAPID CITY/REGIONAL AIRPORT; S', 13.1, 'SSE', 44.0453, -103.0569),
        ('72764', 'BISMARCK/MUN.; ND.', 344.2, 'NNE', 46.7717, -100.7594),
        ('72562', 'NORTH PLATTE/LEE BIRD; NE.', 389.9, 'SSE', 41.1328, -100.7),
    ],
    'KSSC': [
        ('72208', 'CHARLESTON/MUN.; SC.', 127.1, 'SSE', 32.895, -80.0275),
        ('72317', 'GREENSBORO/G.-HIGH PT.; NC.', 240.5, 'NNE', 36.0981, -79.9428),
        ('72305', 'NEWPORT; NC.', 341.1, 'ENE', 34.7761, -76.8767),
    ],
    'KDMA': [
        ('72274', 'TUCSON; AZ', 9.5, 'NW', 32.2278, -110.9558),
        ('74626', 'WFO PHOENIX;', 174.0, 'NW', 33.45, -111.95),
        ('74005', 'YUMA PRVGR', 305.0, 'WNW', 32.8636, -114.033),
    ],
    'KVBG': [
        ('72393', 'VANDENBERG AFB; CA. (72393-0)', 2.4, 'NE', 34.75, -120.5666),
        ('72381', 'EDWARDS AFB; CA.', 245.7, 'E', 34.9167, -117.9),
        ('74612', 'CHINA LAKE; NAF; CA.', 283.8, 'ENE', 35.6833, -117.6833),
    ],
    'KFTK': [
        ('72327', 'NASHVILLE/METROPOLITAN; TN.', 193.0, 'SSW', 36.2333, -86.55),
        ('72426', 'WILMINGTON; OH.', 251.5, 'NE', 39.4214, -83.8217),
        ('74560', 'LINCOLN; IL.', 383.1, 'NW', 40.1517, -89.3383),
    ],
    'PAED': [
        ('70273', 'ANCHORAGE/INT.; AK', 13.1, 'SW', 61.1567, -149.9863),
        ('70231', 'MCGRATH; AK', 354.6, 'NW', 62.9583, -155.5977),
        ('70261', 'FAIRBANKS/INT.; AK', 408.6, 'NNE', 64.8161, -147.8766),
    ],
    'PABI': [
        ('70261', 'FAIRBANKS/INT.; AK', 138.2, 'NW', 64.8161, -147.8766),
        ('70273', 'ANCHORAGE/INT.; AK', 383.5, 'SW', 61.1567, -149.9863),
        ('70231', 'MCGRATH; AK', 503.2, 'W', 62.9583, -155.5977),
    ],
    'RJTY': [
        ('47646', 'TATENO', 78.0, 'ENE', 36.0581, 140.1258),
        ('47600', 'WAJIMA', 285.2, 'NW', 37.3914, 136.8953),
        ('47678', 'HACHIJOJIMA', 294.8, 'S', 33.1217, 139.7792),
    ],
    'KWRB': [
        ('72215', 'PEACHTREE CITY; GA.', 120.9, 'NW', 33.3558, -84.5672),
        ('72214', 'TALLAHASSEE/MUN.; FL.', 252.9, 'SSW', 30.4461, -84.2994),
        ('72206', 'JACKSONVILLE/INTNL.; FL.', 299.2, 'SE', 30.4839, -81.7011),
    ],
    'KCBM': [
        ('72230', 'BIRMINGHAM; AL', 164.1, 'ESE', 33.1789, -86.7822),
        ('72235', 'JACKSON/ALLEN C. THOMPSON FIEL', 211.9, 'SW', 32.3189, -90.08),
        ('72327', 'NASHVILLE/METROPOLITAN; TN.', 335.5, 'NNE', 36.2333, -86.55),
    ],
    'KBIX': [
        ('72233', 'SLIDELL/MUN. LA', 87.1, 'W', 30.3369, -89.825),
        ('72221', 'VALPARAISO/EGLIN AFB; FL.', 230.7, 'E', 30.4833, -86.5167),
        ('72235', 'JACKSON/ALLEN C. THOMPSON FIEL', 238.5, 'NNW', 32.3189, -90.08),
    ],
    'KVPS': [
        ('72221', 'VALPARAISO/EGLIN AFB; FL.', 0.9, 'E', 30.4833, -86.5167),
        ('72214', 'TALLAHASSEE/MUN.; FL.', 213.4, 'E', 30.4461, -84.2994),
        ('72230', 'BIRMINGHAM; AL', 300.7, 'N', 33.1789, -86.7822),
    ],
    'KHRT': [
        ('72221', 'VALPARAISO/EGLIN AFB; FL.', 17.7, 'ENE', 30.4833, -86.5167),
        ('72214', 'TALLAHASSEE/MUN.; FL.', 229.2, 'E', 30.4461, -84.2994),
        ('72233', 'SLIDELL/MUN. LA', 300.9, 'W', 30.3369, -89.825),
    ],
    'KPAM': [
        ('72221', 'VALPARAISO/EGLIN AFB; FL.', 101.2, 'WNW', 30.4833, -86.5167),
        ('72214', 'TALLAHASSEE/MUN.; FL.', 129.6, 'ENE', 30.4461, -84.2994),
        ('72230', 'BIRMINGHAM; AL', 363.9, 'NNW', 33.1789, -86.7822),
    ],
    'KMCF': [
        ('72210', 'TAMPA BAY AREA; FL.', 20.4, 'SSE', 27.7053, -82.4006),
        ('74794', 'CAPE KENNEDY', 203.9, 'ENE', 28.4667, -80.55),
        ('72206', 'JACKSONVILLE/INTNL.; FL.', 302.3, 'NNE', 30.4839, -81.7011),
    ],
    'KBAD': [
        ('72248', 'SHREVEPORT/REG.; LA.', 17.7, 'WSW', 32.4511, -93.8414),
        ('72240', 'LAKE CHARLES/MUN.; LA.', 266.1, 'S', 30.1253, -93.2161),
        ('72340', 'LITTLE ROCK/ADAMS FLD; AR.', 291.3, 'NNE', 34.835, -92.2594),
    ],
    'KTIK': [
        ('72357', 'NORMAN/MAX WESTHEIMER A; OK.', 26.5, 'S', 35.1808, -97.4378),
        ('74646', 'LAMONT', 132.2, 'N', 36.6, -97.5),
        ('72249', 'FORT WORTH; TX.', 287.0, 'S', 32.835, -97.2986),
    ],
    'KLTS': [
        ('72357', 'NORMAN/MAX WESTHEIMER A; OK.', 176.6, 'ENE', 35.1808, -97.4378),
        ('72363', 'AMARILLO/INTL.; TX.', 231.1, 'WNW', 35.2331, -101.7091),
        ('74646', 'LAMONT', 268.0, 'NE', 36.6, -97.5),
    ],
    'KDYS': [
        ('72265', 'MIDLAND/MIDLAND REG. AIRTERM', 226.1, 'WSW', 31.9425, -102.1891),
        ('72249', 'FORT WORTH; TX.', 243.7, 'ENE', 32.835, -97.2986),
        ('72261', 'DEL RIO/INT.; TX.', 352.2, 'SSW', 29.3744, -100.9183),
    ],
    'KCVS': [
        ('72363', 'AMARILLO/INTL.; TX.', 175.1, 'ENE', 35.2331, -101.7091),
        ('72265', 'MIDLAND/MIDLAND REG. AIRTERM', 290.9, 'SSE', 31.9425, -102.1891),
        ('72365', 'ALBUQUERQUE/INT.; NM.', 310.3, 'WNW', 35.0378, -106.6219),
    ],
    'KSZL': [
        ('72440', 'SPRINGFIELD/MUN.; MO.', 167.4, 'S', 37.2347, -93.4014),
        ('72456', 'TOPEKA/MUN.; KS.', 183.9, 'WNW', 39.0722, -95.6305),
        ('72558', 'VALLEY; NE.', 374.2, 'NW', 41.32, -96.3669),
    ],
    'KOFF': [
        ('72558', 'VALLEY; NE.', 44.1, 'WNW', 41.32, -96.3669),
        ('72456', 'TOPEKA/MUN.; KS.', 229.2, 'S', 39.0722, -95.6305),
        ('72562', 'NORTH PLATTE/LEE BIRD; NE.', 401.2, 'W', 41.1328, -100.7),
    ],
    'KSKF': [
        ('72251', 'CORPUS CHRISTI/INT.; TX.', 207.8, 'SSE', 27.7789, -97.5055),
        ('72261', 'DEL RIO/INT.; TX.', 226.5, 'W', 29.3744, -100.9183),
        ('72249', 'FORT WORTH; TX.', 401.8, 'NNE', 32.835, -97.2986),
    ],
    'KRND': [
        ('72251', 'CORPUS CHRISTI/INT.; TX.', 209.2, 'SSE', 27.7789, -97.5055),
        ('72261', 'DEL RIO/INT.; TX.', 257.2, 'W', 29.3744, -100.9183),
        ('72249', 'FORT WORTH; TX.', 378.1, 'NNE', 32.835, -97.2986),
    ],
    'KDLF': [
        ('72261', 'DEL RIO/INT.; TX.', 13.0, 'W', 29.3744, -100.9183),
        ('72265', 'MIDLAND/MIDLAND REG. AIRTERM', 316.4, 'NNW', 31.9425, -102.1891),
        ('72251', 'CORPUS CHRISTI/INT.; TX.', 365.6, 'ESE', 27.7789, -97.5055),
    ],
    'KLSV': [
        ('72388', 'LAS VEGAS', 25.0, 'SSW', 36.0471, -115.1846),
        ('74612', 'CHINA LAKE; NAF; CA.', 246.2, 'WSW', 35.6833, -117.6833),
        ('72381', 'EDWARDS AFB; CA.', 297.8, 'WSW', 34.9167, -117.9),
    ],
    'KLUF': [
        ('74626', 'WFO PHOENIX;', 41.1, 'ESE', 33.45, -111.95),
        ('74005', 'YUMA PRVGR', 171.1, 'WSW', 32.8636, -114.033),
        ('72376', 'FLAGSTAFF; AZ', 195.0, 'NNE', 35.23, -111.8216),
    ],
    'KHMN': [
        ('72364', 'SANTA TERESA; NM.', 122.2, 'SSW', 31.8728, -106.698),
        ('72365', 'ALBUQUERQUE/INT.; NM.', 247.6, 'N', 35.0378, -106.6219),
        ('72265', 'MIDLAND/MIDLAND REG. AIRTERM', 381.6, 'ESE', 31.9425, -102.1891),
    ],
    'KBAB': [
        ('72489', 'RENO; NV.', 148.6, 'ENE', 39.5681, -119.7966),
        ('72493', 'OAKLAND/METROP. OAKLAND INT.;', 170.2, 'SSW', 37.7444, -122.2236),
        ('72597', 'MEDFORD/MEDFORD-JACKSON COUNTY', 379.4, 'NNW', 42.3769, -122.8822),
    ],
    'KSUU': [
        ('72493', 'OAKLAND/METROP. OAKLAND INT.;', 61.5, 'SSW', 37.7444, -122.2236),
        ('72489', 'RENO; NV.', 236.2, 'NE', 39.5681, -119.7966),
        ('72393', 'VANDENBERG AFB; CA. (72393-0)', 408.0, 'SSE', 34.75, -120.5666),
    ],
    'KLFI': [
        ('72402', 'WALLOPS ISLAND; VA.', 121.1, 'NE', 37.9333, -75.4833),
        ('72403', 'WASHINGTON/DULLES INT.; VA.', 228.4, 'NNW', 38.95, -77.45),
        ('72305', 'NEWPORT; NC.', 261.4, 'S', 34.7761, -76.8767),
    ],
    'KDOV': [
        ('72402', 'WALLOPS ISLAND; VA.', 133.1, 'S', 37.9333, -75.4833),
        ('72403', 'WASHINGTON/DULLES INT.; VA.', 172.6, 'W', 38.95, -77.45),
        ('72501', 'UPTON; NY.', 293.8, 'NE', 40.865, -72.8628),
    ],
    'KADW': [
        ('72403', 'WASHINGTON/DULLES INT.; VA.', 52.6, 'WNW', 38.95, -77.45),
        ('72402', 'WALLOPS ISLAND; VA.', 155.8, 'SE', 37.9333, -75.4833),
        ('72520', 'PITTSBURGH/GREATER PITTSBURGH', 343.2, 'NW', 40.5167, -80.2167),
    ],
    'EGUN': [
        ('03693', 'SHOEBURYNESS', 92.8, 'SSE', 51.5547, 0.8269),
        ('03354', 'NOTTINGHAM', 137.2, 'WNW', 53.0056, -1.2511),
        ('03882', 'HERSTMONCEUX', 163.1, 'S', 50.8994, 0.3169),
    ],
    'EGUL': [
        ('03693', 'SHOEBURYNESS', 96.7, 'S', 51.5547, 0.8269),
        ('03354', 'NOTTINGHAM', 138.9, 'WNW', 53.0056, -1.2511),
        ('03882', 'HERSTMONCEUX', 168.7, 'S', 50.8994, 0.3169),
    ],
    'ETAR': [
        ('10618', 'IDAR-OBERSTEIN', 34.6, 'NW', 49.6927, 7.3263),
        ('10739', 'STUTTGART/SCHNARRENBERG', 134.7, 'ESE', 48.8281, 9.2),
        ('10410', 'ESSEN-BREDENEY', 223.3, 'NNW', 51.4041, 6.9677),
    ],
    'ETAD': [
        ('10618', 'IDAR-OBERSTEIN', 55.2, 'SE', 49.6927, 7.3263),
        ('10410', 'ESSEN-BREDENEY', 159.6, 'N', 51.4041, 6.9677),
        ('06458', 'BEAUVECHAIN', 161.5, 'WNW', 50.7456, 4.7633),
    ],
    'KHIF': [
        ('72572', 'SALT LAKE CITY/INTNL UT.', 37.7, 'S', 40.7722, -111.9552),
        ('74003', 'DUGWAY PRVGR', 133.2, 'SW', 40.1667, -112.9333),
        ('72582', 'ELKO; NV.', 318.5, 'W', 40.86, -115.7422),
    ],
    'KFFO': [
        ('72426', 'WILMINGTON; OH.', 49.7, 'SSE', 39.4214, -83.8217),
        ('72632', 'WHITE LAKE; MI.', 321.7, 'N', 42.6989, -83.4714),
        ('72520', 'PITTSBURGH/GREATER PITTSBURGH', 333.1, 'ENE', 40.5167, -80.2167),
    ],
    'KBLV': [
        ('74560', 'LINCOLN; IL.', 184.4, 'NNE', 40.1517, -89.3383),
        ('72440', 'SPRINGFIELD/MUN.; MO.', 344.2, 'WSW', 37.2347, -93.4014),
        ('74455', 'QUAD CITY; IA.', 347.2, 'N', 41.6114, -90.5817),
    ],
    'KMUO': [
        ('72681', 'BOISE/MUN.; ID.', 66.2, 'NNW', 43.5672, -116.2113),
        ('72582', 'ELKO; NV.', 241.5, 'S', 40.86, -115.7422),
        ('74003', 'DUGWAY PRVGR', 400.6, 'SE', 40.1667, -112.9333),
    ],
    'KEDW': [
        ('72381', 'EDWARDS AFB; CA.', 2.6, 'WNW', 34.9167, -117.9),
        ('74612', 'CHINA LAKE; NAF; CA.', 87.9, 'NNE', 35.6833, -117.6833),
        ('72293', 'SAN DIEGO/MIRAMAR; NAS; CA.', 241.1, 'SSE', 32.8333, -117.1166),
    ],
    'PGUA': [
        ('91212', 'WEATHER FORECAST OFFICE; GUAM;', 17.8, 'SW', 13.4767, 144.7944),
        ('91413', 'YAP/CAROLINE IS.', 874.5, 'WSW', 9.4833, 138.0667),
        ('91334', 'TRUK/CAROLINE IS.', 1017.9, 'SE', 7.45, 151.8333),
    ],
    'RODN': [
        ('47909', 'NAZE', 282.8, 'NE', 28.385, 129.4947),
        ('47945', 'MINAMIDAITOJIMA', 350.5, 'E', 25.8289, 131.2286),
        ('47918', 'ISHIGAKIJIMA', 426.1, 'WSW', 24.3367, 124.1644),
    ],
    'RKSO': [
        ('47122', 'OSAN (US/KOR-AFB)', 1.0, 'NNE', 37.1, 127.0333),
        ('47230', 'DEOKJEOKBUKRI', 84.4, 'WNW', 37.2645, 126.103),
        ('47135', 'CHUPUNGNYEONG', 129.5, 'SE', 36.2202, 127.9946),
    ],
    'RKJK': [
        ('47269', 'ANMADO', 81.3, 'SW', 35.3469, 126.0305),
        ('47158', 'GWANGJU AB', 88.6, 'S', 35.1167, 126.8),
        ('47135', 'CHUPUNGNYEONG', 128.8, 'ENE', 36.2202, 127.9946),
    ],
    'KLSF': [
        ('72215', 'PEACHTREE CITY; GA.', 121.1, 'NNE', 33.3558, -84.5672),
        ('72230', 'BIRMINGHAM; AL', 193.3, 'WNW', 33.1789, -86.7822),
        ('72214', 'TALLAHASSEE/MUN.; FL.', 218.6, 'SSE', 30.4461, -84.2994),
    ],
    'KFBG': [
        ('72317', 'GREENSBORO/G.-HIGH PT.; NC.', 141.1, 'NW', 36.0981, -79.9428),
        ('72305', 'NEWPORT; NC.', 191.4, 'ESE', 34.7761, -76.8767),
        ('72318', 'BLACKSBURG; VA.', 266.1, 'NNW', 37.2039, -80.4142),
    ],
    'KOZR': [
        ('72221', 'VALPARAISO/EGLIN AFB; FL.', 117.1, 'SW', 30.4833, -86.5167),
        ('72214', 'TALLAHASSEE/MUN.; FL.', 163.3, 'SE', 30.4461, -84.2994),
        ('72230', 'BIRMINGHAM; AL', 234.3, 'NNW', 33.1789, -86.7822),
    ],
    'KHOP': [
        ('72327', 'NASHVILLE/METROPOLITAN; TN.', 97.6, 'ESE', 36.2333, -86.55),
        ('72230', 'BIRMINGHAM; AL', 393.8, 'S', 33.1789, -86.7822),
        ('74560', 'LINCOLN; IL.', 418.9, 'NNW', 40.1517, -89.3383),
    ],
    'KGRK': [
        ('72249', 'FORT WORTH; TX.', 201.8, 'NNE', 32.835, -97.2986),
        ('72261', 'DEL RIO/INT.; TX.', 351.8, 'WSW', 29.3744, -100.9183),
        ('72251', 'CORPUS CHRISTI/INT.; TX.', 368.2, 'S', 27.7789, -97.5055),
    ],
    'KFRI': [
        ('72456', 'TOPEKA/MUN.; KS.', 97.7, 'E', 39.0722, -95.6305),
        ('72558', 'VALLEY; NE.', 253.9, 'N', 41.32, -96.3669),
        ('74646', 'LAMONT', 280.8, 'SSW', 36.6, -97.5),
    ],
    'KFHU': [
        ('72274', 'TUCSON; AZ', 91.6, 'NW', 32.2278, -110.9558),
        ('74626', 'WFO PHOENIX;', 256.0, 'NW', 33.45, -111.95),
        ('72364', 'SANTA TERESA; NM.', 346.7, 'E', 31.8728, -106.698),
    ],
    'KGRF': [
        ('72797', 'QUILLAYUTE; WA.', 176.5, 'WNW', 47.9339, -124.5602),
        ('72694', 'SALEM/MCNARY; OR.', 243.5, 'S', 44.9092, -123.0083),
        ('72786', 'SPOKANE; WA.', 378.8, 'ENE', 47.6806, -117.6266),
    ],
    'KFAF': [
        ('72402', 'WALLOPS ISLAND; VA.', 133.3, 'NE', 37.9333, -75.4833),
        ('72403', 'WASHINGTON/DULLES INT.; VA.', 214.9, 'NNW', 38.95, -77.45),
        ('72305', 'NEWPORT; NC.', 263.3, 'S', 34.7761, -76.8767),
    ],
    'KMUI': [
        ('72403', 'WASHINGTON/DULLES INT.; VA.', 182.0, 'SSW', 38.95, -77.45),
        ('72402', 'WALLOPS ISLAND; VA.', 293.7, 'SSE', 37.9333, -75.4833),
        ('72520', 'PITTSBURGH/GREATER PITTSBURGH', 309.0, 'W', 40.5167, -80.2167),
    ],
    'KFCS': [
        ('72476', 'GRAND JUNCTION/WALKER FIELD; C', 330.3, 'W', 39.12, -108.525),
        ('72451', 'DODGE CITY/MUN.; KS.', 429.9, 'ESE', 37.7614, -99.9686),
        ('72365', 'ALBUQUERQUE/INT.; NM.', 437.4, 'SSW', 35.0378, -106.6219),
    ],
    'ETIC': [
        ('10771', 'KUEMMERSBRUCK', 29.9, 'S', 49.4283, 11.9016),
        ('10548', 'MEININGEN', 147.2, 'NW', 50.5611, 10.3771),
        ('10868', 'OBERSCHLEIA HEIM (AEROLOGY)', 163.9, 'S', 48.2446, 11.5525),
    ],
    'ETOU': [
        ('10618', 'IDAR-OBERSTEIN', 82.0, 'WSW', 49.6927, 7.3263),
        ('10739', 'STUTTGART/SCHNARRENBERG', 149.6, 'SSE', 48.8281, 9.2),
        ('10548', 'MEININGEN', 156.2, 'ENE', 50.5611, 10.3771),
    ],
    'PHHI': [
        ('91165', 'LIHUE; KAUAI; HAWAII', 146.2, 'WNW', 21.9933, -159.3466),
        ('91285', 'HILO HI; HAWAII', 367.2, 'ESE', 19.7183, -155.0583),
    ],
    'RKSG': [
        ('47122', 'OSAN (US/KOR-AFB)', 15.3, 'N', 37.1, 127.0333),
        ('47230', 'DEOKJEOKBUKRI', 88.9, 'WNW', 37.2645, 126.103),
        ('47135', 'CHUPUNGNYEONG', 119.2, 'SE', 36.2202, 127.9946),
    ],
    'SCBA': [
        ('87860', 'COMODORO RIVADAVIA AERO', 328.0, 'E', -45.7923, -67.4619),
        ('85799', 'PUERTO MONTT', 510.5, 'NNW', -41.435, -73.0978),
        ('85934', 'PUNTA ARENAS', 790.6, 'S', -53.0016, -70.8386),
    ],
    'SAWG': [
        ('85934', 'PUNTA ARENAS', 186.6, 'SSW', -53.0016, -70.8386),
        ('87860', 'COMODORO RIVADAVIA AERO', 660.7, 'NNE', -45.7923, -67.4619),
        ('88889', 'MOUNT PLEASANT AIRPORT', 747.7, 'E', -51.82, -58.4481),
    ],
    'SAZS': [
        ('85799', 'PUERTO MONTT', 165.2, 'WSW', -41.435, -73.0978),
        ('87715', 'NEUQUEN AERO', 354.7, 'NE', -38.952, -68.1367),
        ('87860', 'COMODORO RIVADAVIA AERO', 595.9, 'SSE', -45.7923, -67.4619),
    ],
    'SAWE': [
        ('85934', 'PUNTA ARENAS', 222.1, 'WNW', -53.0016, -70.8386),
        ('88889', 'MOUNT PLEASANT AIRPORT', 661.9, 'ENE', -51.82, -58.4481),
        ('87860', 'COMODORO RIVADAVIA AERO', 888.5, 'N', -45.7923, -67.4619),
    ],
    'SCCI': [
        ('85934', 'PUNTA ARENAS', 1.1, 'E', -53.0016, -70.8386),
        ('87860', 'COMODORO RIVADAVIA AERO', 838.3, 'NNE', -45.7923, -67.4619),
        ('88889', 'MOUNT PLEASANT AIRPORT', 850.6, 'E', -51.82, -58.4481),
    ],
    'SAZN': [
        ('87715', 'NEUQUEN AERO', 0.4, 'ESE', -38.952, -68.1367),
        ('87623', 'SANTA ROSA AERO', 428.7, 'NE', -36.5931, -64.2799),
        ('85799', 'PUERTO MONTT', 503.5, 'SW', -41.435, -73.0978),
    ],
    'SAWC': [
        ('85934', 'PUNTA ARENAS', 313.6, 'SSE', -53.0016, -70.8386),
        ('87860', 'COMODORO RIVADAVIA AERO', 604.7, 'NE', -45.7923, -67.4619),
        ('88889', 'MOUNT PLEASANT AIRPORT', 964.6, 'ESE', -51.82, -58.4481),
    ],
    'SAVE': [
        ('85799', 'PUERTO MONTT', 229.3, 'NW', -41.435, -73.0978),
        ('87860', 'COMODORO RIVADAVIA AERO', 434.5, 'SE', -45.7923, -67.4619),
        ('87715', 'NEUQUEN AERO', 507.1, 'NNE', -38.952, -68.1367),
    ],
}


def sites_for(icao: str) -> list[tuple[str, str, float, str, float, float]]:
    """Nearest radiosonde sites for a station (empty if the station is unknown)."""
    return UPPER_AIR.get(icao.upper(), [])


def nearest_wmo(icao: str) -> str | None:
    """The single closest sounding site's WMO id, or None."""
    got = sites_for(icao)
    return got[0][0] if got else None
