"""Regenerate src/forecaster/radarsites.py from IEM's NEXRAD network geojson.

The radar-site catalog is a STATIC in-repo table (pure geography: id, name, state,
country, lat, lon) used by imagery.nearest_radar(). Re-run this only if the NEXRAD
network membership changes; the output is committed so the tool needs no network to
resolve the nearest radar.
"""

import json
import urllib.request
from pathlib import Path

_URL = "https://mesonet.agron.iastate.edu/geojson/network/NEXRAD.geojson"
_OUT = Path(__file__).resolve().parents[1] / "src" / "forecaster" / "radarsites.py"
_UA = "artificial-forecaster/0.1 (research; contact wquinten@proton.me)"

req = urllib.request.Request(_URL, headers={"User-Agent": _UA})
with urllib.request.urlopen(req, timeout=60) as resp:
    doc = json.loads(resp.read().decode())

rows = []
for f in doc["features"]:
    p = f["properties"]
    lon, lat = f["geometry"]["coordinates"]
    rows.append((f["id"], p.get("sname") or "", p.get("state") or "",
                 p.get("country") or "", round(lat, 3), round(lon, 3)))
rows.sort()

lines = [
    '"""WSR-88D radar site catalog (static, v1).',
    "",
    "Generated by scripts/build_radarsites.py from IEM's NEXRAD network geojson",
    "(mesonet.agron.iastate.edu/geojson/network/NEXRAD.geojson). Pure geography: id",
    "(3-letter NEXRAD site -- the key IEM's RIDGE/radmap products use), name, state,",
    "country, lat, lon. Used by imagery.nearest_radar() to pick the closest site.",
    '"""',
    "",
    "# (site_id, name, state, country, lat, lon)",
    "RADARS: list[tuple[str, str, str, str, float, float]] = [",
]
lines += [f"    ({r[0]!r}, {r[1]!r}, {r[2]!r}, {r[3]!r}, {r[4]}, {r[5]})," for r in rows]
lines += ["]", ""]
_OUT.write_text("\n".join(lines))
print(f"wrote {_OUT} with {len(rows)} sites")
