"""Regenerate src/forecaster/neighbors.py -- the static nearest-neighbor roster.

For each roster station (stations.STATIONS) this finds the 5 closest OTHER METAR-reporting
airfields within 150 km and freezes them, mirroring build_radarsites.py. The candidate
catalog comes from AWC's `stationinfo` bbox product (a STABLE membership list -- every known
METAR site in the box, not just whoever is reporting right now), so the output is
deterministic and `--check` can verify reproducibility. Ranking + bearings via geo.py;
elev_delta (neighbor minus home, meters) comes free from stationinfo `elev`.

The tool that reads this (get_nearby_obs) never touches AWC -- neighbor OBS flow only through
the leakage-safe DB seam (store.copy_obs). This table is pure geography.

  uv run python scripts/build_neighbors.py            # regenerate the committed table
  uv run python scripts/build_neighbors.py --check     # recompute, diff vs committed, don't write
"""

import sys
from math import cos, radians
from pathlib import Path

from forecaster import awc
from forecaster.geo import nearest_n
from forecaster.stations import icaos

_OUT = Path(__file__).resolve().parents[1] / "src" / "forecaster" / "neighbors.py"
_N = 5
_MAX_KM = 150.0
_LAT_PAD = 1.5                      # deg; > 150 km / 111 km-per-deg, with margin


def _home_info(icao: str) -> tuple[float, float, int]:
    """(lat, lon, elev_m) for a roster station from AWC stationinfo."""
    for r in awc._get("stationinfo", {"ids": icao, "format": "json"}) or []:
        if r.get("lat") is not None and r.get("lon") is not None:
            return float(r["lat"]), float(r["lon"]), int(r.get("elev") or 0)
    raise ValueError(f"AWC has no station info for {icao}")


def _candidates(lat: float, lon: float) -> dict[str, tuple[float, float, int]]:
    """Every METAR-reporting station in a ~150 km bbox: icao -> (lat, lon, elev_m)."""
    lon_pad = min(_LAT_PAD / max(cos(radians(lat)), 0.2), 8.0)   # widen with latitude
    bbox = f"{lat - _LAT_PAD},{lon - lon_pad},{lat + _LAT_PAD},{lon + lon_pad}"
    out: dict[str, tuple[float, float, int]] = {}
    for r in awc._get("stationinfo", {"bbox": bbox, "format": "json"}) or []:
        icao = r.get("icaoId")
        if not icao or "METAR" not in (r.get("siteType") or []):
            continue
        if r.get("lat") is None or r.get("lon") is None:
            continue
        out[icao] = (float(r["lat"]), float(r["lon"]), int(r.get("elev") or 0))
    return out


def build() -> dict[str, list[tuple[str, float, str, int]]]:
    table: dict[str, list[tuple[str, float, str, int]]] = {}
    for home in icaos():
        hlat, hlon, helev = _home_info(home)
        cands = _candidates(hlat, hlon)
        cands.pop(home, None)
        catalog = [(icao, la, lo) for icao, (la, lo, _e) in cands.items()]
        ranked = nearest_n(hlat, hlon, catalog, n=_N, max_km=_MAX_KM)
        table[home] = [
            (icao, dist, brg, cands[icao][2] - helev) for icao, dist, brg in ranked
        ]
        print(f"{home}: {len(table[home])} neighbors "
              f"({', '.join(f'{i}@{d:.0f}km' for i, d, _b, _e in table[home])})")
    return table


def render(table: dict[str, list[tuple[str, float, str, int]]]) -> str:
    lines = [
        '"""Static nearest-neighbor roster (generated by scripts/build_neighbors.py).',
        "",
        "For each roster station: the 5 closest OTHER METAR airfields within 150 km, from",
        "AWC's stationinfo catalog. Pure geography (icao, dist_km, 16-pt bearing FROM the home",
        "station, elev_delta_m = neighbor minus home). get_nearby_obs uses this to pick which",
        "stations to read; the OBS themselves come only from the leakage-safe DB seam, never",
        "a live fetch. Regenerate/verify with build_neighbors.py [--check].",
        '"""',
        "",
        "# home_icao -> [(neighbor_icao, dist_km, bearing, elev_delta_m), ...] nearest first",
        "NEIGHBORS: dict[str, list[tuple[str, float, str, int]]] = {",
    ]
    for home in table:
        lines.append(f"    {home!r}: [")
        for icao, dist, brg, de in table[home]:
            lines.append(f"        ({icao!r}, {dist}, {brg!r}, {de}),")
        lines.append("    ],")
    lines += [
        "}",
        "",
        "",
        "def neighbors_of(icao: str) -> list[tuple[str, float, str, int]]:",
        '    """Nearest-neighbor rows for a station (empty list if none/off-roster)."""',
        "    return NEIGHBORS.get(icao.upper(), [])",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    check = "--check" in sys.argv[1:]
    table = build()
    text = render(table)
    if check:
        current = _OUT.read_text() if _OUT.exists() else ""
        if current == text:
            print("\nCHECK PASS: committed neighbors.py matches a fresh build.")
            return 0
        print("\nCHECK FAIL: committed neighbors.py differs from a fresh build.")
        return 1
    _OUT.write_text(text)
    print(f"\nwrote {_OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
